# to install formatter, do `rustup component add rustfmt --toolchain nightly`
# to run formatter, run `cargo +nightly fmt`
# see here for available rules: https://rust-lang.github.io/rustfmt/
unstable_features = true
max_width = 80
error_on_line_overflow = true
error_on_unformatted = true
use_small_heuristics = "Max"
trailing_comma = "Never"
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
