name: "Backend"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    name: "cargo fmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Rustfmt Check
        run: cargo +nightly fmt --check
  clippy:
    name: "cargo clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - run: cargo clippy -- -Dwarnings
  unittest:
    name: "cargo test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Test and generate code coverage
        run: cargo llvm-cov --lcov --output-path core.lcov --workspace --all-features
      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          files: ./core.lcov
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
          fail_ci_if_error: true
  deps:
    name: "cargo udeps"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: aig787/cargo-udeps-action@v1
        with:
          args: "--all-targets"
